name: Release Notes
on:
  pull_request:
    types: [closed,labeled]
    branches:
      - master
  issues:
    types: [closed,reopened,labeled]
  push:
    branches:
      - master
    paths:
      - ".github/workflows/release-notes.yml"
      - ".github/release-drafter.yml"
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
